### ISSUE TITLE
Save to SD card

### ISSUE THREAD

**Issue by paulohlcosta** [alanesq/CameraWifiMotion#1]
This is a very useful project, I am following it and would like see it working!

**Comment by alanesq** [comment]
The project is now pretty much fully working, if you are referring to the use of an SD-card, I have just tested it and it is working ok for me?
At the moment it saves a jpg file and a separate text file with time/date info., I need to look in to finding a better way of doing this?
btw-if using sd card you can not use the flash (this is a limitation of the hardware as the sdcard uses the led control i/o pin).

**Comment by paulohlcosta** [comment]
Nice! I haven't heard about this flash/SD limitations. 

Yes, I would like to have it saved in the SD card, pictures with a 1000 ms interval. This guy made it save, seems easy, but his code has no motion detection.

https://randomnerdtutorials.com/esp32-cam-take-photo-save-microsd-card/

My current code:

esp32-cam_motion_detection_sdcard.ino

The error:

diff	23	29
diff	23	30
diff	23	31
Changed 768 out of 768
Motion detected
JPEG buffer len: 76800
Picture file name: /picture22.jpg
E (2959) sdmmc_cmd: sdmmc_read_sectors_dma: 

sdmmc_send_cmd returned 0xffffffff
E (2959) diskio_sdmmc: sdmmc_read_blocks failed (-1)
E (3962) sdmmc_req: sdmmc_host_wait_for_event 

returned 0x107
E (3962) sdmmc_cmd: sdmmc_read_sectors_dma: 

sdmmc_send_cmd returned 0x107
E (3963) diskio_sdmmc: sdmmc_read_blocks failed 

(263)

**Comment by alanesq** [comment]
The flash is on gpio pin 4 which is also used for the sd card so if your code is trying to turn the flash on this could account for your errors on the sd card.
I have some code in my setup which tries to load the sdcard and if successful sets a flag which tells the rest of the code not to try and use the flash.

**Comment by paulohlcosta** [comment]
Sorry, here's the link to the code:
https://github.com/paulohlcosta/esp32-cam_motion_detection_sdcard/blob/master/esp32-cam_motion_detection_sdcard.ino

**Comment by boontherd12346** [comment]
#4
