### ISSUE TITLE
serialDebug not declared in ota.h

### ISSUE THREAD

**Issue by kennethgomez01** [alanesq/CameraWifiMotion#11]
`'serialDebug' was not declared in this scope`

**Comment by kennethgomez01** [comment]
I believe you delete bool serialDebug = 1;

**Comment by JoeThumper** [comment]
Thanks Mr. Gomez. Due to your remark i could get it compiled. I also had to include >\n at some places within the quotation marks, because of another compiler rant. After that it compiled. Have to try it now.

**Comment by alanesq** [comment]
no longer an issue
