### ISSUE TITLE
should main.cpp be in the  CameraWifiMotion/CameraWifiMotion/ folder ?

### ISSUE THREAD

**Issue by dallday** [alanesq/CameraWifiMotion#18]
I tried compiling this with the Arduino IDE  and it had loads of errors about duplicated entries etc.,

After some investigation I saw that the main.cpp redefined a lot that was the the CameraWifiMotion,ino 

I removed the main.cpp from the folder for the Arduino IDE and it seems to compile and work successfully.

Is the main.cpp used for one of the other compiler options ?

Thanks for a very interesting project 

David

**Comment by faisal-saddique** [comment]
I guess main.cpp is used for platformio

**Comment by alanesq** [comment]
Yes, I converted over to PlatformIO but now I believe its no longer supported so in the process of moving to the new Arduino IDE...
As you did, just rename main.cpp to CameraWifiMotion.ini   (I should have put this in the notes)
