### ISSUE TITLE
Add vflip/hflip button

### ISSUE THREAD

**Issue by thomas-pegot** [alanesq/CameraWifiMotion#6]
Hello,

Nice project. 
It would be a good feature to add vflip/hflip. I have done it myself in local since you already have the var `cameraImageInvert`.

**Comment by alanesq** [comment]
Hi,
I had considered this but I felt the screen was too cluttered as it is and this is something you would only really need to set up once for each camera so I just left it as a setting you can change in the code (as you have seen).
